# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: info.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ninfo.proto\x12\x0egrpc.health.v1\"\x1f\n\x0bInfoRequest\x12\x10\n\x08selector\x18\x01 \x01(\t\"\xe1\x02\n\x0cInfoResponse\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0e\n\x06uptime\x18\x05 \x01(\x03\x12\x38\n\x06labels\x18\x06 \x03(\x0b\x32(.grpc.health.v1.InfoResponse.LabelsEntry\x12:\n\x07metrics\x18\x07 \x03(\x0b\x32).grpc.health.v1.InfoResponse.MetricsEntry\x12\x12\n\nbuild_hash\x18\x08 \x01(\t\x12\x12\n\nbuild_time\x18\t \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x16\n\x14InfoLanguagesRequest\"J\n\x15InfoLanguagesResponse\x12\x14\n\x0ctarget_langs\x18\x01 \x03(\t\x12\x1b\n\x13\x64\x65\x66\x61ult_source_lang\x18\x02 \x01(\t2\xa2\x01\n\x04Info\x12@\n\x03\x41ll\x12\x1b.grpc.health.v1.InfoRequest\x1a\x1c.grpc.health.v1.InfoResponse\x12X\n\tLanguages\x12$.grpc.health.v1.InfoLanguagesRequest\x1a%.grpc.health.v1.InfoLanguagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFORESPONSE_LABELSENTRY']._loaded_options = None
  _globals['_INFORESPONSE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_INFORESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_INFORESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_INFOREQUEST']._serialized_start=30
  _globals['_INFOREQUEST']._serialized_end=61
  _globals['_INFORESPONSE']._serialized_start=64
  _globals['_INFORESPONSE']._serialized_end=417
  _globals['_INFORESPONSE_LABELSENTRY']._serialized_start=324
  _globals['_INFORESPONSE_LABELSENTRY']._serialized_end=369
  _globals['_INFORESPONSE_METRICSENTRY']._serialized_start=371
  _globals['_INFORESPONSE_METRICSENTRY']._serialized_end=417
  _globals['_INFOLANGUAGESREQUEST']._serialized_start=419
  _globals['_INFOLANGUAGESREQUEST']._serialized_end=441
  _globals['_INFOLANGUAGESRESPONSE']._serialized_start=443
  _globals['_INFOLANGUAGESRESPONSE']._serialized_end=517
  _globals['_INFO']._serialized_start=520
  _globals['_INFO']._serialized_end=682
# @@protoc_insertion_point(module_scope)
